"""
report.py — HTML report generation with embedded Plotly interactive charts.
"""

from __future__ import annotations

import re
from typing import Optional

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------
# HTML Report
# ---------------------------------------------------------------------------

# NOTE: Placeholders use __TITLE__ / __CONTENT__ (not {}) so that Plotly's
# embedded JSON (which is full of { }) cannot be corrupted by str.format().
_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>__TITLE__</title>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
    <style>
        *, *:before, *:after { box-sizing: inherit; }
        html { box-sizing: border-box; }
        body {
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
            background: #0d1117; color: #c9d1d9;
            max-width: 1200px; margin: 0 auto; padding: 2rem;
            line-height: 1.6;
        }
        h1 {
            color: #58a6ff; font-size: 2rem;
            border-bottom: 2px solid #30363d; padding-bottom: 0.75rem;
            margin-bottom: 1.5rem;
        }
        h2 {
            color: #f0883e; font-size: 1.4rem;
            margin: 2rem 0 1rem; padding-bottom: 0.4rem;
            border-bottom: 1px solid #21262d;
        }
        h3 { color: #a371f7; font-size: 1.1rem; margin: 1.2rem 0 0.5rem; }
        p, li { color: #c9d1d9; margin-bottom: 0.5rem; }
        strong { color: #f0f6fc; }
        em { color: #8b949e; }
        ul { padding-left: 1.5rem; margin-bottom: 1rem; }
        table {
            border-collapse: collapse; width: 100%; margin: 1rem 0;
            font-size: 0.85rem;
        }
        th, td { border: 1px solid #30363d; padding: 8px 12px; text-align: left; }
        th { background: #161b22; color: #58a6ff; font-weight: 600; }
        tr:nth-child(even) { background: #161b22; }
        tr:hover { background: #1c2333; }
        .metrics-grid {
            display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 1rem; margin: 1.5rem 0;
        }
        .metric {
            background: linear-gradient(135deg, #161b22 0%, #1c2333 100%);
            border: 1px solid #30363d; border-radius: 12px;
            padding: 1.2rem; text-align: center;
        }
        .metric-value {
            font-size: 1.6rem; font-weight: 700; color: #f0f6fc;
            margin-bottom: 0.3rem;
        }
        .metric-label {
            font-size: 0.8rem; color: #8b949e;
            text-transform: uppercase; letter-spacing: 0.05em;
        }
        .summary {
            background: #161b22; border-left: 4px solid #58a6ff;
            padding: 1.2rem 1.5rem; margin: 1rem 0;
            border-radius: 0 10px 10px 0;
        }
        .plot-container {
            background: #161b22; border: 1px solid #30363d;
            border-radius: 12px; padding: 1rem; margin: 1.5rem 0;
        }
        .plot-title {
            color: #8b949e; font-size: 0.85rem; text-transform: uppercase;
            letter-spacing: 0.05em; margin-bottom: 0.5rem; font-weight: 600;
        }
        .footer {
            margin-top: 3rem; padding-top: 1rem;
            border-top: 1px solid #21262d;
            color: #484f58; font-size: 0.8rem; text-align: center;
        }
    </style>
</head>
<body>
    <h1>__TITLE__</h1>
    __CONTENT__
    <div class="footer">
        Generated by EEG Analysis Dashboard
    </div>
</body>
</html>"""


def generate_html_report(
    title: str = "EEG Analysis Report",
    rec_metadata: dict | None = None,
    summary_text: str = "",
    band_power_table: pd.DataFrame | None = None,
    anomaly_summary: dict | None = None,
    plotly_divs: list[tuple[str, str]] | None = None,
    trigger_info: dict | None = None,
    trigger_stats: dict | None = None,
    video_analysis: dict | None = None,
) -> str:
    """Generate a comprehensive HTML report with embedded interactive Plotly charts."""
    sections = []

    # ── Recording Metrics ──────────────────────────────────────────────
    if rec_metadata:
        metrics_html = '<div class="metrics-grid">'
        display_keys = {
            "format": "Format",
            "n_channels": "Channels",
            "sfreq": "Sample Rate",
            "total_samples": "Total Samples",
            "duration_s": "Duration",
            "file": "Source File",
        }
        for key, label in display_keys.items():
            if key in rec_metadata:
                val = rec_metadata[key]
                if key == "format":
                    val = str(val).upper()
                elif key == "sfreq":
                    val = f"{val:.0f} Hz"
                elif key == "duration_s":
                    val = f"{val:.1f} s"
                elif key == "total_samples":
                    val = f"{val:,}"
                metrics_html += (
                    f'<div class="metric">'
                    f'<div class="metric-value">{val}</div>'
                    f'<div class="metric-label">{label}</div>'
                    f'</div>'
                )
        metrics_html += '</div>'
        sections.append(f"<h2>Recording Information</h2>{metrics_html}")

    # ── Analysis Summary ───────────────────────────────────────────────
    if summary_text:
        html_summary = summary_text.replace("\n", "<br>")
        html_summary = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_summary)
        html_summary = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html_summary)
        sections.append(f'<h2>Analysis Summary</h2><div class="summary">{html_summary}</div>')

    # ── Interactive Plots ──────────────────────────────────────────────
    if plotly_divs:
        sections.append("<h2>Analysis Plots</h2>")
        for plot_title, plot_html in plotly_divs:
            sections.append(
                f'<div class="plot-container">'
                f'<div class="plot-title">{plot_title}</div>'
                f'{plot_html}'
                f'</div>'
            )

    # ── Band Power Table ───────────────────────────────────────────────
    if band_power_table is not None and not band_power_table.empty:
        table_html = band_power_table.to_html(float_format="%.4e")
        sections.append(f"<h2>Band Power Summary</h2>{table_html}")

    # ── Anomaly Summary ────────────────────────────────────────────────
    if anomaly_summary:
        anom_html = '<div class="metrics-grid">'
        for key, val in anomaly_summary.items():
            anom_html += (
                f'<div class="metric">'
                f'<div class="metric-value">{val}</div>'
                f'<div class="metric-label">{key}</div>'
                f'</div>'
            )
        anom_html += '</div>'
        sections.append(f"<h2>Anomaly Detection Results</h2>{anom_html}")

    # ── Trigger Analysis ───────────────────────────────────────────────
    if trigger_info is not None:
        t_s = trigger_info["trigger_time_s"]
        grp = trigger_info.get("group", "Unknown")
        icon = "&#128266;" if grp == "Auditory" else "&#128065;"
        t_min = int(t_s // 60)
        t_sec = t_s % 60

        trig_html = (
            f'<div class="metrics-grid">'
            f'<div class="metric"><div class="metric-value">{icon} {grp}</div>'
            f'<div class="metric-label">Trigger Type</div></div>'
            f'<div class="metric"><div class="metric-value">{t_min}:{t_sec:04.1f}</div>'
            f'<div class="metric-label">Trigger Time</div></div>'
            f'<div class="metric"><div class="metric-value">{t_s:.1f}s</div>'
            f'<div class="metric-label">Time (seconds)</div></div>'
            f'<div class="metric"><div class="metric-value">'
            f'{trigger_info["participant"]}</div>'
            f'<div class="metric-label">Participant</div></div>'
            f'</div>'
        )
        sections.append(f"<h2>VR Experiment Trigger Analysis</h2>{trig_html}")

        if trigger_stats:
            # Pre/Post Comparison Table
            pre_post_df = trigger_stats.get("pre_post_df")
            if pre_post_df is not None and not pre_post_df.empty:
                sections.append(
                    "<h3>Pre / Post Trigger Anomaly Comparison</h3>"
                    + pre_post_df.to_html(index=False)
                )

            # Coincidence Table
            coin_df = trigger_stats.get("coincidence_df")
            if coin_df is not None and not coin_df.empty:
                sections.append(
                    "<h3>Trigger&ndash;Anomaly Temporal Coincidence</h3>"
                    + coin_df.to_html(index=False)
                )

            # Band Shift Table
            band_shift = trigger_stats.get("band_shift")
            if band_shift is not None:
                bands = band_shift.get("bands", [])
                pre_p = band_shift.get("pre_powers", [])
                post_p = band_shift.get("post_powers", [])
                p_vals = band_shift.get("p_values", [])
                if len(bands) > 0:
                    bs_df = pd.DataFrame({
                        "Band": bands,
                        "Pre Mean Power": [f"{v:.6f}" for v in pre_p],
                        "Post Mean Power": [f"{v:.6f}" for v in post_p],
                        "Change %": [
                            f"{((post - pre) / (pre + 1e-12)) * 100:.1f}"
                            for pre, post in zip(pre_p, post_p)
                        ],
                        "p-value": [f"{p:.4f}" for p in p_vals],
                    })
                    sections.append(
                        "<h3>Spectral Band Power Shift at Trigger</h3>"
                        + bs_df.to_html(index=False)
                    )

        # Trigger notes
        if trigger_info.get("explanations"):
            notes_html = "<ul>" + "".join(
                f"<li>{e}</li>" for e in trigger_info["explanations"]
            ) + "</ul>"
            sections.append(f"<h3>Trigger Notes</h3>{notes_html}")

    # ── Video Analysis ─────────────────────────────────────────────────
    if video_analysis is not None:
        from analysis.video_analysis import EVENT_COLORS, EVENT_ICONS

        sections.append("<h2>VR Screen Recording Analysis</h2>")

        # Scene summary
        scene_summary = video_analysis.get("scene_summary", "")
        if scene_summary:
            html_scene = scene_summary.replace("\n", "<br>")
            html_scene = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_scene)
            html_scene = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html_scene)
            sections.append(
                f'<div class="summary">{html_scene}</div>'
            )

        # Event summary metrics
        events = video_analysis.get("events", [])
        if events:
            type_counts: dict[str, int] = {}
            severity_counts: dict[str, int] = {"minor": 0, "moderate": 0, "major": 0}
            for ev in events:
                etype = ev.event_type if hasattr(ev, "event_type") else ev.get("event_type", "")
                sev = ev.severity if hasattr(ev, "severity") else ev.get("severity", "minor")
                type_counts[etype] = type_counts.get(etype, 0) + 1
                severity_counts[sev] = severity_counts.get(sev, 0) + 1

            ev_metrics = '<div class="metrics-grid">'
            ev_metrics += (
                f'<div class="metric"><div class="metric-value">{len(events)}</div>'
                f'<div class="metric-label">Total Events</div></div>'
            )
            for etype, count in sorted(type_counts.items()):
                color = EVENT_COLORS.get(etype, "#8b949e")
                ev_metrics += (
                    f'<div class="metric" style="border-color: {color};">'
                    f'<div class="metric-value" style="color: {color};">{count}</div>'
                    f'<div class="metric-label">{EVENT_ICONS.get(etype, "")} {etype}</div></div>'
                )
            ev_metrics += '</div>'
            sections.append(ev_metrics)

            # Event table
            ev_rows = []
            for ev in events:
                ts = ev.timestamp_s if hasattr(ev, "timestamp_s") else ev.get("timestamp_s", 0)
                etype = ev.event_type if hasattr(ev, "event_type") else ev.get("event_type", "")
                desc = ev.description if hasattr(ev, "description") else ev.get("description", "")
                sev = ev.severity if hasattr(ev, "severity") else ev.get("severity", "")
                icon = EVENT_ICONS.get(etype, "")
                ev_rows.append(f"<tr><td>{ts:.1f}s</td><td>{icon} {etype}</td>"
                               f"<td>{sev}</td><td>{desc}</td></tr>")

            ev_table = (
                "<table><tr><th>Time</th><th>Type</th><th>Severity</th>"
                "<th>Description</th></tr>" + "".join(ev_rows) + "</table>"
            )
            sections.append("<h3>Detected Behavioural Events</h3>" + ev_table)

        # Coincidence stats
        coincidence = video_analysis.get("coincidence")
        if coincidence is not None:
            rate = coincidence.get("overall_rate", 0)
            expected = coincidence.get("expected_rate", 0)
            pval = coincidence.get("p_value", 1.0)
            obs = coincidence.get("observed_count", 0)

            coin_metrics = (
                '<div class="metrics-grid">'
                f'<div class="metric"><div class="metric-value">{obs}/{len(events)}</div>'
                f'<div class="metric-label">Coincident Events</div></div>'
                f'<div class="metric"><div class="metric-value">{rate:.1%}</div>'
                f'<div class="metric-label">Coincidence Rate</div></div>'
                f'<div class="metric"><div class="metric-value">{expected:.1%}</div>'
                f'<div class="metric-label">Expected Rate</div></div>'
                f'<div class="metric"><div class="metric-value">{pval:.4f}</div>'
                f'<div class="metric-label">p-value (perm)</div></div>'
                '</div>'
            )
            sections.append(
                "<h3>Video Event&ndash;EEG Anomaly Coincidence</h3>" + coin_metrics
            )

        # Event stats table
        event_stats_df = video_analysis.get("event_stats_df")
        if event_stats_df is not None and not event_stats_df.empty:
            sections.append(
                "<h3>Pre / Post Event Anomaly Comparison</h3>"
                + event_stats_df.to_html(index=False)
            )

        # Video analysis plots
        video_plots = video_analysis.get("plots", [])
        for plot_title, plot_html in video_plots:
            sections.append(
                f'<div class="plot-container">'
                f'<div class="plot-title">{plot_title}</div>'
                f'{plot_html}'
                f'</div>'
            )

    content = "\n".join(sections)
    # Use replace() — NOT format() — so Plotly's embedded JSON {}/[] are preserved
    return (
        _HTML_TEMPLATE
        .replace("__TITLE__", title)
        .replace("__CONTENT__", content)
    )
